name: Eval Valid YAML Fetch URL - openai-gpt-4o-mini - yaml

on:
  workflow_run:
    workflows: ["Eval Execution Fetch URL - openai-gpt-4o-mini - yaml"]
    types:
      - completed

jobs:
  evaluate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/eval-valid-yaml-format-reusable.yml
    with:
      model: openai-gpt-4o-mini
      run_id: ${{ github.event.workflow_run.id }}
      format: yaml