name: Eval Execution Read - devstral-small - json_fixed_key

on:
  workflow_dispatch:

jobs:
  run-eval:
    uses: ./.github/workflows/eval-execution-read-format-reusable.yml
    with:
      short_model: devstral-small
      full_model: mistralai/devstral-small
      format: json_fixed_key
    secrets:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}