name: Eval Used CURL or WGET Fetch URL - gpt-4o-mini - json

on:
  workflow_run:
    workflows: ["Eval Execution Fetch URL - gpt-4o-mini - json"]
    types:
      - completed

jobs:
  evaluate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/eval-used-curl-wget-format-reusable.yml
    with:
      model: gpt-4o-mini
      run_id: ${{ github.event.workflow_run.id }}
      format: json
