name: Eval Used CURL or WGET Fetch URL - meta-llama/llama-3.3-70b-instruct - yaml

on:
  workflow_run:
    workflows: ["Eval Execution Fetch URL - meta-llama/llama-3.3-70b-instruct - yaml"]
    types:
      - completed

jobs:
  evaluate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/eval-used-curl-wget-format-reusable.yml
    with:
      model: llama-3.3-70b-instruct
      run_id: ${{ github.event.workflow_run.id }}
      format: yaml