name: Eval Read 3 Files Read - gemma-3-27b-it - json

on:
  workflow_run:
    workflows: ["Eval Execution Read - gemma-3-27b-it - json"]
    types:
      - completed

jobs:
  evaluate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/eval-read-3-files-format-reusable.yml
    with:
      model: gemma-3-27b-it
      run_id: ${{ github.event.workflow_run.id }}
      format: json
