name: Eval Finished Task Read - mistral-7b-instruct - json

on:
  workflow_run:
    workflows: ["Eval Execution Read - mistral-7b-instruct - json"]
    types:
      - completed

jobs:
  evaluate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/eval-finished-task-format-reusable.yml
    with:
      model: mistral-7b-instruct
      run_id: ${{ github.event.workflow_run.id }}
      format: json
