name: Eval Valid YAML Fetch URL - google/gemini-2.5-flash-lite - yaml

on:
  workflow_run:
    workflows: ["Eval Execution Fetch URL - google/gemini-2.5-flash-lite - yaml"]
    types:
      - completed

jobs:
  evaluate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/eval-valid-yaml-format-reusable.yml
    with:
      model: google-gemini-2.5-flash-lite
      run_id: ${{ github.event.workflow_run.id }}
      format: yaml