name: Eval Read 8 Files Read - gpt-4o-mini - json_fixed_key

on:
  workflow_run:
    workflows: ["Eval Execution Read - gpt-4o-mini - json_fixed_key"]
    types:
      - completed

jobs:
  evaluate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/eval-read-8-files-format-reusable.yml
    with:
      model: gpt-4o-mini
      run_id: ${{ github.event.workflow_run.id }}
      format: json_fixed_key