name: Eval Finished Task Read - openai/gpt-5-nano - yaml

on:
  workflow_run:
    workflows: ["Eval Execution Read - openai/gpt-5-nano - yaml"]
    types:
      - completed

jobs:
  evaluate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/eval-finished-task-format-reusable.yml
    with:
      model: openai-gpt-5-nano
      run_id: ${{ github.event.workflow_run.id }}
      format: yaml