name: Eval Finished Task Read - devstral-small - json_fixed_key

on:
  workflow_run:
    workflows: ["Eval Execution Read - devstral-small - json_fixed_key"]
    types:
      - completed

jobs:
  evaluate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/eval-finished-task-format-reusable.yml
    with:
      model: devstral-small
      run_id: ${{ github.event.workflow_run.id }}
      format: json_fixed_key