name: Eval Finished Task Read - gpt-oss-120b-exacto - yaml

on:
  workflow_run:
    workflows: ["Eval Execution Read - gpt-oss-120b-exacto - yaml"]
    types:
      - completed

jobs:
  evaluate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/eval-finished-task-format-reusable.yml
    with:
      model: gpt-oss-120b-exacto
      run_id: ${{ github.event.workflow_run.id }}
      format: yaml